language: c
script: make && make fs.img
deploy:
  provider: releases
  api_key:
    secure: czsGbPLRhuysd7UTudQMo1bR5bpiD9D7p2gBWDmSO9SoBbt7d89IN2F7XI71ifDO5jmpgidk6HhbeQI88vCBxfOdsyhOcsN4HpNg1gfktvPgXdeRzO/xU33NFoRjQjhHqFSX9F1XZ4LVSao3tzcfxh9qsJ4wmQcR8UBLAyyg8botspC9KN9wdRJWaNz5zytl+aZX5dGhyVIridmW9WyWouus6Hs1PAybkQWkJ7lF1JFVHh235PRpK7sNB2q1Bu+X5IKR8Xalhqjq367RF2BDHdpTi22/d28GDk7yeHKYhkvaKl2vkiZTUWXDevnbahKXGdojNrXtug+R20yoRA6SwaY19nhlZbSUswfgZbxvbEGy4moxl9GvnlZL94imOYhEcvdfET9rOBIb7vO7ITty76mB/SYwRKE7kLuzpI5wcSHzrKcjBAKcnPIJ31cqJMHPrg2MdpzxlFFyaZ0MhzXWTpo0HhzM0Nv2Tbe2RUJyPIX+Z/TixdKuGL7Q5ghxgqQa2GJ6ZgPWV1njxBJNdTewwwwS/BjkAF766SGXtWazbRAqLM8YAsGuig5RUSlhsXcyE99wpis7W9Rpclosmk0mLaCm7RFWXdC8JpfVrrCd18pruB5Sy9JSUDR2GCisZJCU4Eq5XKAo3qgCdgwH6ivzW9535bd2Sn7ejIlTIOKSyMo=
  file:     
  - fs.img     
  - xv6.img   
  skip_cleanup: true
  on:
    repo: iwigol/xv6-public
    branch: project_1
    tags: true
